<a href="https://colab.research.google.com/github/wesromero9/Tesla/blob/main/Tesla_Stock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd

In [63]:
df=pd.read_csv("TSLA.csv")

In [64]:
df

           Date        Open        High  ...       Close   Adj Close     Volume
0    2020-08-24  425.256012  425.799988  ...  402.839996  402.839996  100318000
1    2020-08-25  394.977997  405.589996  ...  404.667999  404.667999   53294500
2    2020-08-26  412.000000  433.200012  ...  430.634003  430.634003   71197000
3    2020-08-27  436.092010  459.119995  ...  447.750000  447.750000  118465000
4    2020-08-28  459.023987  463.697998  ...  442.679993  442.679993  100406000
..          ...         ...         ...  ...         ...         ...        ...
247  2021-08-17  672.659973  674.580017  ...  665.710022  665.710022   23721300
248  2021-08-18  669.750000  695.770020  ...  688.989990  688.989990   20349400
249  2021-08-19  678.210022  686.549988  ...  673.469971  673.469971   14313500
250  2021-08-20  682.849976  692.130005  ...  680.260010  680.260010   14781800
251  2021-08-23  685.442017  712.129883  ...  706.299988  706.299988   20069007

[252 rows x 7 columns]

In [65]:
date_list=list(df['Date'])
date_list

['2020-08-24',
 '2020-08-25',
 '2020-08-26',
 '2020-08-27',
 '2020-08-28',
 '2020-08-31',
 '2020-09-01',
 '2020-09-02',
 '2020-09-03',
 '2020-09-04',
 '2020-09-08',
 '2020-09-09',
 '2020-09-10',
 '2020-09-11',
 '2020-09-14',
 '2020-09-15',
 '2020-09-16',
 '2020-09-17',
 '2020-09-18',
 '2020-09-21',
 '2020-09-22',
 '2020-09-23',
 '2020-09-24',
 '2020-09-25',
 '2020-09-28',
 '2020-09-29',
 '2020-09-30',
 '2020-10-01',
 '2020-10-02',
 '2020-10-05',
 '2020-10-06',
 '2020-10-07',
 '2020-10-08',
 '2020-10-09',
 '2020-10-12',
 '2020-10-13',
 '2020-10-14',
 '2020-10-15',
 '2020-10-16',
 '2020-10-19',
 '2020-10-20',
 '2020-10-21',
 '2020-10-22',
 '2020-10-23',
 '2020-10-26',
 '2020-10-27',
 '2020-10-28',
 '2020-10-29',
 '2020-10-30',
 '2020-11-02',
 '2020-11-03',
 '2020-11-04',
 '2020-11-05',
 '2020-11-06',
 '2020-11-09',
 '2020-11-10',
 '2020-11-11',
 '2020-11-12',
 '2020-11-13',
 '2020-11-16',
 '2020-11-17',
 '2020-11-18',
 '2020-11-19',
 '2020-11-20',
 '2020-11-23',
 '2020-11-24',
 '2020-11-25',
 '2020-11-27',
 '2020-11-30',
 '2020-12-01',
 '2020-12-02',
 '2020-12-03',
 '2020-12-04',
 '2020-12-07',
 '2020-12-08',
 '2020-12-09',
 '2020-12-10',
 '2020-12-11',
 '2020-12-14',
 '2020-12-15',
 '2020-12-16',
 '2020-12-17',
 '2020-12-18',
 '2020-12-21',
 '2020-12-22',
 '2020-12-23',
 '2020-12-24',
 '2020-12-28',
 '2020-12-29',
 '2020-12-30',
 '2020-12-31',
 '2021-01-04',
 '2021-01-05',
 '2021-01-06',
 '2021-01-07',
 '2021-01-08',
 '2021-01-11',
 '2021-01-12',
 '2021-01-13',
 '2021-01-14',
 '2021-01-15',
 '2021-01-19',
 '2021-01-20',
 '2021-01-21',
 '2021-01-22',
 '2021-01-25',
 '2021-01-26',
 '2021-01-27',
 '2021-01-28',
 '2021-01-29',
 '2021-02-01',
 '2021-02-02',
 '2021-02-03',
 '2021-02-04',
 '2021-02-05',
 '2021-02-08',
 '2021-02-09',
 '2021-02-10',
 '2021-02-11',
 '2021-02-12',
 '2021-02-16',
 '2021-02-17',
 '2021-02-18',
 '2021-02-19',
 '2021-02-22',
 '2021-02-23',
 '2021-02-24',
 '2021-02-25',
 '2021-02-26',
 '2021-03-01',
 '2021-03-02',
 '2021-03-03',
 '2021-03-04',
 '2021-03-05',
 '2021-03-08',
 '2021-03-09',
 '2021-03-10',
 '2021-03-11',
 '2021-03-12',
 '2021-03-15',
 '2021-03-16',
 '2021-03-17',
 '2021-03-18',
 '2021-03-19',
 '2021-03-22',
 '2021-03-23',
 '2021-03-24',
 '2021-03-25',
 '2021-03-26',
 '2021-03-29',
 '2021-03-30',
 '2021-03-31',
 '2021-04-01',
 '2021-04-05',
 '2021-04-06',
 '2021-04-07',
 '2021-04-08',
 '2021-04-09',
 '2021-04-12',
 '2021-04-13',
 '2021-04-14',
 '2021-04-15',
 '2021-04-16',
 '2021-04-19',
 '2021-04-20',
 '2021-04-21',
 '2021-04-22',
 '2021-04-23',
 '2021-04-26',
 '2021-04-27',
 '2021-04-28',
 '2021-04-29',
 '2021-04-30',
 '2021-05-03',
 '2021-05-04',
 '2021-05-05',
 '2021-05-06',
 '2021-05-07',
 '2021-05-10',
 '2021-05-11',
 '2021-05-12',
 '2021-05-13',
 '2021-05-14',
 '2021-05-17',
 '2021-05-18',
 '2021-05-19',
 '2021-05-20',
 '2021-05-21',
 '2021-05-24',
 '2021-05-25',
 '2021-05-26',
 '2021-05-27',
 '2021-05-28',
 '2021-06-01',
 '2021-06-02',
 '2021-06-03',
 '2021-06-04',
 '2021-06-07',
 '2021-06-08',
 '2021-06-09',
 '2021-06-10',
 '2021-06-11',
 '2021-06-14',
 '2021-06-15',
 '2021-06-16',
 '2021-06-17',
 '2021-06-18',
 '2021-06-21',
 '2021-06-22',
 '2021-06-23',
 '2021-06-24',
 '2021-06-25',
 '2021-06-28',
 '2021-06-29',
 '2021-06-30',
 '2021-07-01',
 '2021-07-02',
 '2021-07-06',
 '2021-07-07',
 '2021-07-08',
 '2021-07-09',
 '2021-07-12',
 '2021-07-13',
 '2021-07-14',
 '2021-07-15',
 '2021-07-16',
 '2021-07-19',
 '2021-07-20',
 '2021-07-21',
 '2021-07-22',
 '2021-07-23',
 '2021-07-26',
 '2021-07-27',
 '2021-07-28',
 '2021-07-29',
 '2021-07-30',
 '2021-08-02',
 '2021-08-03',
 '2021-08-04',
 '2021-08-05',
 '2021-08-06',
 '2021-08-09',
 '2021-08-10',
 '2021-08-11',
 '2021-08-12',
 '2021-08-13',
 '2021-08-16',
 '2021-08-17',
 '2021-08-18',
 '2021-08-19',
 '2021-08-20',
 '2021-08-23']

In [66]:
len(date_list)

252

In [67]:
price_close=list(df['Close'])
price_close

[402.839996,
 404.667999,
 430.634003,
 447.75,
 442.67999299999997,
 498.32000700000003,
 475.049988,
 447.369995,
 407.0,
 418.320007,
 330.209991,
 366.27999900000003,
 371.339996,
 372.72000099999997,
 419.619995,
 449.76000999999997,
 441.76000999999997,
 423.42999299999997,
 442.14999400000005,
 449.39001500000006,
 424.23001100000005,
 380.359985,
 387.790009,
 407.339996,
 421.200012,
 419.070007,
 429.01000999999997,
 448.160004,
 415.089996,
 425.67999299999997,
 413.980011,
 425.299988,
 425.920013,
 434.0,
 442.299988,
 446.64999400000005,
 461.299988,
 448.880005,
 439.670013,
 430.829987,
 421.94000199999994,
 422.64001500000006,
 425.790009,
 420.630005,
 420.27999900000003,
 424.67999299999997,
 406.019989,
 410.829987,
 388.040009,
 400.51001,
 423.89999400000005,
 420.98001100000005,
 438.089996,
 429.950012,
 421.26000999999997,
 410.359985,
 417.130005,
 411.76001,
 408.5,
 408.089996,
 441.60998499999994,
 486.64001500000006,
 499.26998899999995,
 489.60998499999994,
 521.849976,
 555.380005,
 574.0,
 585.76001,
 567.599976,
 584.76001,
 568.820007,
 593.380005,
 599.039978,
 641.76001,
 649.880005,
 604.47998,
 627.070007,
 609.98999,
 639.830017,
 633.25,
 622.77002,
 655.900024,
 695.0,
 649.8599849999999,
 640.340027,
 645.97998,
 661.77002,
 663.6900019999999,
 665.98999,
 694.780029,
 705.669983,
 729.77002,
 735.1099849999999,
 755.97998,
 816.039978,
 880.0200199999999,
 811.1900019999999,
 849.4400019999999,
 854.409973,
 845.0,
 826.159973,
 844.5499880000001,
 850.4500119999999,
 844.98999,
 846.6400150000001,
 880.7999880000001,
 883.090027,
 864.159973,
 835.429993,
 793.530029,
 839.8099980000001,
 872.7899779999999,
 854.6900019999999,
 849.98999,
 852.2299800000001,
 863.419983,
 849.4600220000001,
 804.820007,
 811.659973,
 816.119995,
 796.219971,
 798.150024,
 787.380005,
 781.299988,
 714.5,
 698.840027,
 742.02002,
 682.219971,
 675.5,
 718.429993,
 686.4400019999999,
 653.200012,
 621.4400019999999,
 597.950012,
 563.0,
 673.580017,
 668.0599980000001,
 699.599976,
 693.72998,
 707.9400019999999,
 676.880005,
 701.8099980000001,
 653.159973,
 654.869995,
 670.0,
 662.159973,
 630.27002,
 640.3900150000001,
 618.710022,
 611.289978,
 635.619995,
 667.929993,
 661.75,
 691.049988,
 691.619995,
 670.969971,
 683.799988,
 677.02002,
 701.97998,
 762.320007,
 732.22998,
 738.849976,
 739.780029,
 714.630005,
 718.98999,
 744.119995,
 719.6900019999999,
 729.400024,
 738.200012,
 704.73999,
 694.400024,
 677.0,
 709.4400019999999,
 684.900024,
 673.599976,
 670.9400019999999,
 663.539978,
 672.369995,
 629.039978,
 617.200012,
 589.8900150000001,
 571.6900019999999,
 589.73999,
 576.830017,
 577.869995,
 563.460022,
 586.780029,
 580.880005,
 606.4400019999999,
 604.6900019999999,
 619.130005,
 630.849976,
 625.219971,
 623.900024,
 605.119995,
 572.840027,
 599.049988,
 605.130005,
 603.590027,
 598.780029,
 610.119995,
 609.8900150000001,
 617.6900019999999,
 599.3599849999999,
 604.869995,
 616.599976,
 623.3099980000001,
 620.830017,
 623.710022,
 656.570007,
 679.820007,
 671.869995,
 688.719971,
 680.76001,
 679.700012,
 677.919983,
 678.900024,
 659.580017,
 644.650024,
 652.8099980000001,
 656.950012,
 685.700012,
 668.539978,
 653.380005,
 650.599976,
 644.219971,
 646.219971,
 660.5,
 655.289978,
 649.26001,
 643.380005,
 657.619995,
 644.780029,
 646.97998,
 677.349976,
 687.200012,
 709.669983,
 709.73999,
 710.919983,
 714.630005,
 699.099976,
 713.76001,
 709.98999,
 707.820007,
 722.25,
 717.169983,
 686.169983,
 665.710022,
 688.98999,
 673.469971,
 680.26001,
 706.299988]

In [68]:
def get_daily_return(old_price,new_price):
  return (new_price-old_price)/old_price

In [69]:
old_price=680.26
new_price=706.29
get_daily_return(old_price,new_price)

0.038264781113103774

In [70]:
price_close[0]

402.839996

In [71]:
price_close[1]

404.667999

In [72]:
get_daily_return(price_close[0],price_close[1])price_close[i],price_close[i,1]))

SyntaxError: ignored

In [ ]:
returns_list=[]
for i in range(0,len(price_close)-1):
  print(i)
  returns_list.append(get_daily_return(price_close[i],price_close[i+1]))

In [ ]:
returns_list

# Excercise part 2

In [ ]:
returns_list [0:5]

In [ ]:
returns_list[-1]

In [ ]:
returns_list[-2]

In [ ]:
def buy_sell(num):
    if num < 0:
        recommendation="Buy"
    else:
        recommendation="Sell"
    return recommendation

In [ ]:
buy_sell(-1)

In [ ]:
buy_sell(1)

In [ ]:
print(list(range(0,len(price_close)-1)))

In [ ]:
returns_list=[]
recommendations_list=[]
for i in range(0,len(price_close)-1):

  output=get_daily_return(price_close[i],price_close[i+1])
  recommendation=buy_sell(output)
  print(i,output,recommendation)
  returns_list.append(output)

In [ ]:
returns_list.insert(0,0)

In [ ]:
len(returns_list)

In [ ]:
recommendations_list.insert(0,"")

In [ ]:
len(recommendations_list)

In [ ]:
summary_df=pd.DataFrame({'Date':date_list,'Closing Price':price_close,'Daily Return':returns_list,'Reco':recommendations_list})

In [ ]:
summary_df